<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <AssemblyName>AlienKeygen</AssemblyName>
    <RootNamespace>AlienKeygen</RootNamespace>
    <Version>3.5.0</Version>
    <Authors>Alien Software Development</Authors>
    <Company>Alien Software Development</Company>
    <Product>Alien Master Keygen - Private Admin Edition</Product>
    <Copyright>Copyright © 2026 Alien Software Development</Copyright>
    <ApplicationIcon>..\Assets\keygen_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\BatToExeConverter\UITheme.cs" Link="UITheme.cs" />
    <Compile Include="..\BatToExeConverter\LicenseManager.cs" Link="LicenseManager.cs" />
    <Compile Include="..\BatToExeConverter\KeygenForm.cs" Link="KeygenForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Assets\**\*.*">
      <Link>Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
