<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <AssemblyName>BatToExePro_Setup</AssemblyName>
    <RootNamespace>BatToExeSetup</RootNamespace>
    <Version>3.5.0</Version>
    <Authors>Alien Software Development</Authors>
    <Company>Alien Software Development</Company>
    <Product>BAT to EXE Converter Pro Studio Setup</Product>
    <Copyright>Copyright © 2026 Alien Software Development</Copyright>
    <ApplicationIcon>..\Assets\installer_icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\BatToExeConverter\UITheme.cs" Link="UITheme.cs" />
    <Compile Include="..\BatToExeConverter\ShellContextMenu.cs" Link="ShellContextMenu.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Release_Build\BatToExePro_Standalone\BatToExeConverter.exe">
      <Link>Payload\BatToExeConverter.exe</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Release_Build\AlienKeygen_Standalone\AlienKeygen.exe">
      <Link>Payload\AlienKeygen.exe</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Assets\**\*.*">
      <Link>Payload\Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </EmbeddedResource>
  </ItemGroup>

</Project>
